### ISSUE TITLE
Support for WFS 1.0.0 / 1.1.0

### ISSUE THREAD

**Issue by JakobMiksch** [GastonZalba/ol-wfs-capabilities#1]
Thanks for the useful library. Unfortunately I have to work with WFS 1.0.0 / 1.1.0 and this project only supports WFS 2.0.0.
Do you think it is possible to also support WFS 1.0.0 / 1.1.0 within this library?
If yes, I could try to implement this

**Comment by GastonZalba** [comment]
Hi, yes. I think it should be implemented. If I remember correctly I have a local branch with this started (and abandoned shortly after). Let me see what I have and I'll give you more details.

**Comment by GastonZalba** [comment]
Hi @JakobMiksch , I uploaded the branch [next](https://github.com/GastonZalba/ol-wfs-capabilities/tree/next) (a work in progress) with:
- new tests to check all the versions (they're probably going to need some tweaking, but it's a start) 
- updated the example page to allow manual checking between versions (open it with `npm run watch`)
- in the main file:
   * added more NAMESPACE_URIS to decode properly "older" xml attributes
   * added some basic logic to switch parsers between the versions

There is still a lot of work to be done to make all the attributes work, but the basis to do so is already in place. If you want to collaborate, you could clone this branch and work there. Otherwise, probably within the week I can finish it.

**Comment by JakobMiksch** [comment]
Hi @GastonZalba thanks for your message. I was able to setup it up and run the (failing) tests, however I not sure how much capacity I will have within the next time to actually get into the coding. If you want to implement this, I can offer to do testing and review.

**Comment by GastonZalba** [comment]
Hi, I just uploaded in the `next` branch the updated code with 1.0.0 and 1.1.0 versions support. If you can do some testing with your WFS sources, it would be great! If everything is ok I will merge it with the master

**Comment by JakobMiksch** [comment]
@GastonZalba could you create a PR of your `next` branch then I can add some review to the code

**Comment by JakobMiksch** [comment]
@GastonZalba I tried the new functionality with WFS Capabilities documents from both QGIS Server and GeoServer and it seems to work fine. I also loading WFS 2.0.0 still seems to work. I tested it with this URL https://ows-demo.terrestris.de/geoserver/osm/wfs?service=wfs&version=1.1.0&request=GetCapabilities

In my local web application I installed the package via the file system and this also worked.

**Comment by GastonZalba** [comment]
> @GastonZalba could you create a PR of your `next` branch then I can add some review to the code

Did yo still need this? I created the Pull Request but i'm struggling adding a Reviewer (the list is empty and I can't add new users)

**Comment by JakobMiksch** [comment]
> > @GastonZalba could you create a PR of your `next` branch then I can add some review to the code
> 
> Did yo still need this? I created the Pull Request but i'm struggling adding a Reviewer (the list is empty and I can't add new users)

Actually, since you merged my minor PRs, I would not have needed the PR anymore. But I checked the code again and only suggested a minor formatting issue: https://github.com/GastonZalba/ol-wfs-capabilities/pull/5#pullrequestreview-1715275425
